declare const __CODETIME_CLI_VERSION__: string | undefined
// `__CODETIME_CLI_VERSION__` is a build-time injected define. At runtime under
// tsx (tests) the symbol isn't declared at all; `typeof` is the only safe
// guard against ReferenceError — `=== undefined` would throw.
// eslint-disable-next-line unicorn/no-typeof-undefined, unicorn/no-negated-condition
export const PACKAGE_VERSION = typeof __CODETIME_CLI_VERSION__ !== 'undefined' ? __CODETIME_CLI_VERSION__ : '0.1.1'
export const GENERATED_MARKER = 'Generated by codetime.'
// codetime.dev hosts the merged ingest + dashboard. Local development
// against a Nuxt dev server can override via CODETIME_API_URL.
export const DEFAULT_API_URL = 'https://codetime.dev'
// Upper bound on rollups per HTTP request. The byte cap below usually
// kicks in first; this is the safety lid for tiny rollups so we don't
// pack thousands per request and explode latency.
export const DEFAULT_BACKFILL_BATCH_SIZE = 50
// Soft byte cap for the JSON body of a single ingest POST. Keeps us
// safely under common reverse-proxy `client_max_body_size` defaults
// (nginx defaults to 1 MiB). A single oversized rollup will still be
// sent as its own batch and may 413 — that's surfaced to the user.
export const DEFAULT_BACKFILL_BATCH_BYTES = 800 * 1024
export const ROLLUP_BUCKET_MS = 15 * 60 * 1000
export const DEFAULT_HOOK_SYNC_MIN_INTERVAL_SECONDS = 60
