declare const __CODETIME_CLI_VERSION__: string | undefined
// `__CODETIME_CLI_VERSION__` is a build-time injected define. At runtime under
// tsx (tests) the symbol isn't declared at all; `typeof` is the only safe
// guard against ReferenceError — `=== undefined` would throw.
// eslint-disable-next-line unicorn/no-typeof-undefined, unicorn/no-negated-condition
export const PACKAGE_VERSION = typeof __CODETIME_CLI_VERSION__ !== 'undefined' ? __CODETIME_CLI_VERSION__ : '0.1.1'
export const GENERATED_MARKER = 'Generated by codetime.'
// codetime.dev hosts the merged ingest + dashboard. Local development
// against a Nuxt dev server can override via CODETIME_API_URL.
export const DEFAULT_API_URL = 'https://codetime.dev'
export const DEFAULT_BACKFILL_BATCH_SIZE = 500
export const ROLLUP_BUCKET_MS = 15 * 60 * 1000
export const DEFAULT_HOOK_SYNC_MIN_INTERVAL_SECONDS = 60
