import { randomBytes } from 'node:crypto'
import { mkdir, open, readdir, readFile, rename, rm, stat, writeFile } from 'node:fs/promises'
import path from 'node:path'

export const GENERATED_MARKER = 'Generated by codetime.'

export async function pathExists(filePath: string): Promise<boolean> {
  try {
    await stat(filePath)
    return true
  }
  catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
      return false
    }
    throw error
  }
}

export async function readTextIfExists(filePath: string): Promise<string | null> {
  try {
    return await readFile(filePath, 'utf8')
  }
  catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
      return null
    }
    throw error
  }
}

export async function readJsonIfExists(filePath: string): Promise<unknown> {
  const text = await readTextIfExists(filePath)
  return text ? parseJsonFile(filePath, text) : null
}

export function parseJsonFile(filePath: string, text: string): unknown {
  try {
    return JSON.parse(text)
  }
  catch (error) {
    throw new Error(`Could not parse JSON file ${filePath}: ${(error as Error).message}`)
  }
}

/**
 * Like readJsonIfExists, but returns null for corrupt/unparseable content
 * instead of throwing. Use ONLY for disposable, reconstructable caches
 * (sync-local-trigger.json/.lock, backfill-state.json) so a torn or legacy
 * file self-heals to defaults on the next read instead of bricking the CLI.
 * onCorrupt lets a caller that has a ctx log the swallow (e.g. a watermark
 * reset). Durable/agent config reads must keep using readJsonIfExists so
 * genuine corruption stays loud.
 */
export async function readJsonIfExistsTolerant(
  filePath: string,
  onCorrupt?: (error: Error) => void,
): Promise<unknown> {
  const text = await readTextIfExists(filePath)
  if (text === null) {
    return null
  }
  try {
    return JSON.parse(text)
  }
  catch (error) {
    onCorrupt?.(error as Error)
    return null
  }
}

/**
 * Write a file atomically: write a same-dir temp, then rename over the target.
 * rename(2) swaps the inode, so a concurrent reader sees either the whole old
 * file or the whole new one — never a torn/interleaved write. Two racing
 * writers each rename their own temp: last-writer-wins, never a tear.
 *
 * Deliberately NO fsync: tear-freedom comes from rename atomicity alone (a
 * page-cache read after rename always resolves a complete inode). These
 * callers write reconstructable caches, so crash durability has no value, and
 * an unconditional fsync would add hot-path latency plus a real failure mode
 * on fsync-hostile mounts (EINVAL/ENOTSUP) that plain writeFile never had.
 */
export async function writeFileAtomic(
  filePath: string,
  data: string,
  options: { mode?: number } = {},
): Promise<void> {
  const dir = path.dirname(filePath)
  await mkdir(dir, { recursive: true })
  // Sibling temp (never os.tmpdir): keeps rename intra-filesystem, so no EXDEV.
  // pid + Date.now + random => collision-proof; leading dot keeps it hidden.
  const tmpPath = path.join(
    dir,
    `.${path.basename(filePath)}.${process.pid}.${Date.now()}.${randomBytes(6).toString('hex')}.tmp`,
  )
  let handle
  try {
    // 'wx' = O_EXCL: a temp-name collision is a loud EEXIST, never a clobber.
    handle = await open(tmpPath, 'wx', options.mode ?? 0o666)
    await handle.writeFile(data, 'utf8')
    if (options.mode !== undefined) {
      // Force exact bits; the open mode is subject to the process umask.
      await handle.chmod(options.mode)
    }
    await handle.close()
    handle = undefined
    await renameWithRetry(tmpPath, filePath)
  }
  catch (error) {
    if (handle) {
      await handle.close().catch(() => {})
    }
    // Clean the temp on ANY failure (open/write/chmod/rename), not just rename.
    // Swallow cleanup errors so they can never mask the original write failure
    // (e.g. ENOSPC) that the caller needs to see.
    await rm(tmpPath, { force: true }).catch(() => {})
    throw error
  }
}

async function renameWithRetry(from: string, to: string, attempts = 5): Promise<void> {
  // Windows MoveFileExW transiently fails EPERM/EACCES/EBUSY when another handle
  // lacks FILE_SHARE_DELETE, and Node never retries. Bounded backoff (~100ms total
  // across 4 retries), then rethrow. On POSIX the first try always succeeds.
  for (let i = 0; ; i++) {
    try {
      await rename(from, to)
      return
    }
    catch (error) {
      const code = (error as NodeJS.ErrnoException).code
      if (i >= attempts - 1 || (code !== 'EPERM' && code !== 'EACCES' && code !== 'EBUSY')) {
        throw error
      }
      await new Promise(resolve => setTimeout(resolve, 10 * (i + 1)))
    }
  }
}

export async function writeGeneratedFile(
  filePath: string,
  content: string,
  { dryRun, force, onWrite }: {
    dryRun: boolean
    force: boolean
    onWrite: (message: string) => void
  },
): Promise<void> {
  if (dryRun) {
    onWrite(`Would write ${filePath}`)
    return
  }

  const existing = await readTextIfExists(filePath)
  if (existing === content) {
    onWrite(`Already installed ${filePath}`)
    return
  }

  if (existing !== null && !existing.includes(GENERATED_MARKER) && !force) {
    throw new Error(
      `Refusing to overwrite non-codetime file: ${filePath}. Re-run with --force if this is intentional.`,
    )
  }

  await mkdir(path.dirname(filePath), { recursive: true })
  await writeFile(filePath, content, 'utf8')
  onWrite(`Installed ${filePath}`)
}

export async function listJsonlFiles(rootPath: string): Promise<string[]> {
  return listFilesByExtensions(rootPath, ['.jsonl'])
}

export async function listFilesByExtensions(
  rootPath: string,
  extensions: readonly string[],
): Promise<string[]> {
  let info
  try {
    info = await stat(rootPath)
  }
  catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
      return []
    }
    throw error
  }

  if (info.isFile()) {
    return extensions.some(ext => rootPath.endsWith(ext)) ? [rootPath] : []
  }
  if (!info.isDirectory()) {
    return []
  }

  const entries = await readdir(rootPath, { withFileTypes: true })
  const files = await Promise.all(entries.map(async (entry) => {
    const entryPath = path.join(rootPath, entry.name)
    if (entry.isDirectory()) {
      return listFilesByExtensions(entryPath, extensions)
    }
    return entry.isFile() && extensions.some(ext => entry.name.endsWith(ext)) ? [entryPath] : []
  }))

  return files.flat().sort()
}

export async function countDirectoryEntries(candidatePath: string): Promise<number> {
  try {
    const info = await stat(candidatePath)
    if (!info.isDirectory()) {
      if (candidatePath.endsWith('.jsonl')) {
        const text = await readFile(candidatePath, 'utf8')
        return text.split('\n').filter(Boolean).length
      }
      if (candidatePath.endsWith('.json')) {
        return 1
      }
      if (candidatePath.endsWith('.db')) {
        try {
          const { DatabaseSync } = await import('node:sqlite')
          const db = new DatabaseSync(candidatePath, { readOnly: true })
          try {
            const result = db.prepare(
              'SELECT count(*) as cnt FROM session WHERE time_created IS NOT NULL',
            ).get() as { cnt: number }
            return result?.cnt || 0
          }
          finally {
            db.close()
          }
        }
        catch {
          return 0
        }
      }
      return 1
    }
    // Count both .jsonl (codex/claude/pi sessions) and .json (Amp threads)
    // so adapters with different on-disk formats both surface accurate counts.
    const files = await listFilesByExtensions(candidatePath, ['.jsonl', '.json'])
    return files.length
  }
  catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
      return 0
    }
    throw error
  }
}
