import { mkdir, readdir, readFile, stat, writeFile } from 'node:fs/promises'
import path from 'node:path'

export const GENERATED_MARKER = 'Generated by codetime.'

export async function pathExists(filePath: string): Promise<boolean> {
  try {
    await stat(filePath)
    return true
  }
  catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
      return false
    }
    throw error
  }
}

export async function readTextIfExists(filePath: string): Promise<string | null> {
  try {
    return await readFile(filePath, 'utf8')
  }
  catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
      return null
    }
    throw error
  }
}

export async function readJsonIfExists(filePath: string): Promise<unknown> {
  const text = await readTextIfExists(filePath)
  return text ? parseJsonFile(filePath, text) : null
}

export function parseJsonFile(filePath: string, text: string): unknown {
  try {
    return JSON.parse(text)
  }
  catch (error) {
    throw new Error(`Could not parse JSON file ${filePath}: ${(error as Error).message}`)
  }
}

export async function writeGeneratedFile(
  filePath: string,
  content: string,
  { dryRun, force, onWrite }: {
    dryRun: boolean
    force: boolean
    onWrite: (message: string) => void
  },
): Promise<void> {
  if (dryRun) {
    onWrite(`Would write ${filePath}`)
    return
  }

  const existing = await readTextIfExists(filePath)
  if (existing === content) {
    onWrite(`Already installed ${filePath}`)
    return
  }

  if (existing !== null && !existing.includes(GENERATED_MARKER) && !force) {
    throw new Error(
      `Refusing to overwrite non-codetime file: ${filePath}. Re-run with --force if this is intentional.`,
    )
  }

  await mkdir(path.dirname(filePath), { recursive: true })
  await writeFile(filePath, content, 'utf8')
  onWrite(`Installed ${filePath}`)
}

export async function listJsonlFiles(rootPath: string): Promise<string[]> {
  return listFilesByExtensions(rootPath, ['.jsonl'])
}

export async function listFilesByExtensions(
  rootPath: string,
  extensions: readonly string[],
): Promise<string[]> {
  let info
  try {
    info = await stat(rootPath)
  }
  catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
      return []
    }
    throw error
  }

  if (info.isFile()) {
    return extensions.some(ext => rootPath.endsWith(ext)) ? [rootPath] : []
  }
  if (!info.isDirectory()) {
    return []
  }

  const entries = await readdir(rootPath, { withFileTypes: true })
  const files = await Promise.all(entries.map(async (entry) => {
    const entryPath = path.join(rootPath, entry.name)
    if (entry.isDirectory()) {
      return listFilesByExtensions(entryPath, extensions)
    }
    return entry.isFile() && extensions.some(ext => entry.name.endsWith(ext)) ? [entryPath] : []
  }))

  return files.flat().sort()
}

export async function countDirectoryEntries(candidatePath: string): Promise<number> {
  try {
    const info = await stat(candidatePath)
    if (!info.isDirectory()) {
      if (candidatePath.endsWith('.jsonl')) {
        const text = await readFile(candidatePath, 'utf8')
        return text.split('\n').filter(Boolean).length
      }
      if (candidatePath.endsWith('.json')) {
        return 1
      }
      if (candidatePath.endsWith('.db')) {
        try {
          const { DatabaseSync } = await import('node:sqlite')
          const db = new DatabaseSync(candidatePath, { readOnly: true })
          try {
            const result = db.prepare(
              'SELECT count(*) as cnt FROM session WHERE time_created IS NOT NULL',
            ).get() as { cnt: number }
            return result?.cnt || 0
          }
          finally {
            db.close()
          }
        }
        catch {
          return 0
        }
      }
      return 1
    }
    // Count both .jsonl (codex/claude/pi sessions) and .json (Amp threads)
    // so adapters with different on-disk formats both surface accurate counts.
    const files = await listFilesByExtensions(candidatePath, ['.jsonl', '.json'])
    return files.length
  }
  catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
      return 0
    }
    throw error
  }
}
